### ISSUE TITLE
Is it possible to use this library in disabled wallet mode?

### ISSUE THREAD

**Issue by natonnelier** [edescourtis/ebitcoind#5]
In the README file you present examples that assume we have a wallet working. But I would like to create transactions and sign them by providing the keys and hashes needed to do so, since I'm running my node in --disabled-wallet mode.
Is it possible to do it with this library?

**Comment by edescourtis** [comment]
| -disablewallet | Do not load the wallet and disable wallet RPC calls

I guess not since we need RPC calls to work.

**Comment by edescourtis** [comment]
You could load a dummy wallet with no money in it. Just curious, what do you use the -disabled-wallet mode for?
